### PR TITLE
Add dropped packet counter for when ringbuffer is full

### PR DESCRIPTION
**Pull request by mielverkerken**

### CODE REVIEW

**Review by matissecallewaert — CHANGES_REQUESTED** [review]
Everything looks good, but there is one thing that I think you forgot. You allocate memory using the PerCpuArray with maximum one entry, but nowhere that you set it to zero in the beginning. I don't know if it is tested?

**Review by matissecallewaert — APPROVED** [review]
I have tested it and it does set the value automatically to zero (another thing Rust does better than C :wink: )

**Comment by matissecallewaert** [comment]
Is it possible for the print statement of the lost packets to wait after the writer has flushed and then print the lost packets, because now you need to be searching where it was printed in the terminal.

**Comment by mielverkerken** [comment]
Moved printing of dropped packets to straight after printing the duration.

**Review by matissecallewaert — APPROVED** [review]
:rocket:

**Pull request merged**
